### ISSUE TITLE
Duplicate Schema Bug

### ISSUE THREAD

**Issue by Fleshgrinder** [ota-meshi/eslint-plugin-json-schema-validator#345]
I have a YAML file that gets loaded but has no schema associated with it. Whenever I run the plugin without an explicit ignore of that file it fails with:

```

Oops! Something went wrong! :(

ESLint: 9.9.0

Error: Error while loading rule 'json-schema-validator/no-invalid': schema with key or id "https://github.com/howlowck/common-catalog-schema/schema-versions.json" already exists
Occurred while linting /Users/fleshgrinder/Projects/src/<REDACTED>/.catalog.yml
    at Ajv._checkUnique (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/ajv/dist/core.js:466:19)
    at Ajv.addSchema (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/ajv/dist/core.js:234:14)
    at resolveError (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/utils/validator-factory.js:109:29)
    at schemaToValidator (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/utils/validator-factory.js:64:17)
    at compile (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/utils/validator-factory.js:42:12)
    at schemaPathToValidator (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:27:44)
    at getCatalogValidators (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:319:35)
    at /Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:401:69
    at get (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:389:27)
    at get catalog (/Users/fleshgrinder/Projects/src/<REDACTED>/node_modules/eslint-plugin-json-schema-validator/lib/rules/no-invalid.js:401:28)
```

The only workaround I found was to switch to `flat/base` and adding an explicit `ignores: ['.catalog.yml']` to my config. Note that there's actually a schema, but https://github.com/ota-meshi/eslint-plugin-json-schema-validator/issues/343 and https://github.com/ota-meshi/eslint-plugin-json-schema-validator/issues/344 prevent me from validating it.

**Comment by ota-meshi** [comment]
Can you share a repository where we can reproduce the issue?
That will help us debug it.

**Comment by Fleshgrinder** [comment]
I made quite some changes to my setup and am not able to reproduce it myself by now. Nor am I able to create a standalone MRE. I'll close this issue for now, and will reopen it in case I stumble over it again. Sorry for the inconvenience, I should have created an MRE right away, my bad.
