### ISSUE TITLE
Failed to load plugin 'json-schema-validator' declared in '.eslintrc.js' No valid exports main found for eslint-utils

### ISSUE THREAD

**Issue by Talaween** [ota-meshi/eslint-plugin-json-schema-validator#77]
I have installed the plugin to validate json files according to a custom schema, however, when this plugin is installed and referenced in the .eslintrc.js file, running the eslint command:  `eslint --ext ts,tsx,js,json --quiet .` generates this error, I upgraded eslint to v7.30 but nothing changed.

```
Oops! Something went wrong! :(

ESLint: 7.30.0

Error: Failed to load plugin 'json-schema-validator' declared in '.eslintrc.js': No valid exports main found for '/home/mahmoud/project-ui/node_modules/eslint-utils'
Referenced from: /home/mahmoud/project-ui/.eslintrc.js
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (/home/mahmoud/project-ui/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/mahmoud/project-ui/node_modules/jsonc-eslint-parser/lib/parser/convert.js:4:24)
    at Module._compile (/home/mahmoud/project-ui/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
I can't reproduce your problem. Could you please share a minimal repository to reproduce this issue?

**Comment by Talaween** [comment]
thank you for your quick response, I found the problem, this happens with node v13.5, I upgraded node to v16.4.1 and it disappeared
